include:
  - board: mwave_33
    artifact-name: ansi-windows
  - board: mwave_33
    artifact-name: ansi-mac
    cmake-args: -DKEYMAP_FILE=/tmp/zmk-config/config/mwave_33_mac.keymap
  - board: mwave_33
    artifact-name: iso-windows
    cmake-args: -DKEYMAP_FILE=/tmp/zmk-config/config/mwave_33_iso.keymap
  - board: mwave_33
    snippet: zmk-usb-logging
    artifact-name: ansi-windows-logging
  - board: mwave_33
    cmake-args: -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y
    artifact-name: ansi-settings-reset
